[greeter]
background = /usr/share/backgrounds/leptocline/leptocline-wallpaper.png
theme-name = Greybird-dark
icon-theme-name = Papirus-Dark
font-name = Sans 11
xft-antialias = true
xft-hintstyle = hintslight
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %a %d %b  %H:%M
position = 50%,center 55%,center
hide-user-image = true
